name: Run github actions
on: [pull_request_target]
jobs:
  upload-app-to-appsweep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Upload app to AppSweep with Gradle
        env:
          APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
        run: ./gradlew uploadToAppSweepRelease